#!/usr/bin/ruby
NETS = [["10.100.131", "home", "10.100.131.106"],
        ["10.99.99", "office", "10.99.99.138"]]

ip = `arp -a`.lines.detect{|l| l.include? "0:c:29:21:c5:1e"}.scan(/\((.*)\)/).first.first

puts "IP: #{ip}"
exec "ssh -A kallen@#{ip}"
