colo xoria256

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'tpope/vim-fugitive'
Plugin 'guns/vim-clojure-static'
Plugin 'tpope/vim-fireplace'
Plugin 'tpope/vim-leiningen'
Plugin 'vim-scripts/paredit.vim'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'jlanzarotta/bufexplorer'
call vundle#end()

syntax on
filetype plugin indent on

set nocompatible
set backspace=indent,eol,start

set expandtab
set softtabstop=4
set shiftwidth=4
set tabstop=4
set smarttab

set number
set wmh=0
set ruler
set mousehide
set mouse=a

set incsearch
set hlsearch

set autoindent
set hidden

set wildmenu
set wildmode=longest,list

nmap <c-h> <c-w>h
nmap <c-l> <c-w>l
nmap <c-j> <c-w>j
nmap <c-k> <c-w>k
nmap <silent> <esc>h :tabprev<CR>
nmap <silent> <esc>j :bn<CR>
nmap <silent> <esc>k :bp<CR>
nmap <silent> <esc>l :tabnext<CR>

map <silent> <F4> :silent noh<CR>

map!  <C-c>	    <esc>

map <silent> <leader>e :Eval<CR>
map <silent> <leader>r :Require<CR>
map <silent> <leader>p :RainbowParenthesesToggle<CR>
